apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: testdast 
  janus-idp.io/tekton: testdast
  backstage.io/kubernetes-id: testdast
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testdast
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  