apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testdast
  janus-idp.io/tekton: testdast
  backstage.io/kubernetes-id: testdast
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testdast
resources:
- deployment.yaml
- route.yaml
- service.yaml
